image: node:latest

stages:
    - publish
    
publish:
    stage: publish
    only:
        - master
    script:
        - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
        - npm publish
    