language: node_js
node_js:
  - "node"

before_install:
  - printf "https://registry.npmjs.org/\n//registry.npmjs.org/:_authToken=${NPM_TOKEN}"

deploy:
  provider: npm
  email: tomas.parok@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master